language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
  - sudo mkdir -p /cgroup
  - sudo cp test/cgconfig.conf /etc/.
install:
  - sudo apt-get -qq install rake bison git gperf libcgroup-dev
  - gem install rake
script: 
  - rake all test
