language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libcgroup-dev cgroup-lite
  - gem install rake
  - sudo service cgroup-lite start
script: 
  - rake all test
