language: c
compiler:
  - gcc
  - clang
services:
  - cgconfig
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libcgroup-dev
  - gem install rake
script: 
  - rake all test
