language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libcgroup-dev lxc
  - gem install rake
script: 
  - rake all test
