# build on centos6 for glibc 2.12 or earlier
centos6:
  dockerfile: Dockerfile.centos6
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile

# build on ubuntu 14_04 for glibc 2.14 or later binary like centos7
ubuntu14_04:
  dockerfile: Dockerfile.ubuntu14_14
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile
