# for centos6 glibc 2.12
centos6:
  dockerfile: Dockerfile.centos6
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile

# for ubuntu 14_04 glibc 2.14 or later
ubuntu14_04:
  dockerfile: Dockerfile.ubuntu14_14
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile
